name: Verify

on:
  push:
  pull_request:
  workflow_call:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.4.0

      - name: Use Node 16
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '16'

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ./node_modules
            ./node
          key: yarn-v3-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-${{ github.run_id }}
          restore-keys: |
            yarn-v3-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-
            yarn-v3-${{ runner.os }}-

      - name: Install
        run: yarn install

      - name: Format Check
        run: yarn run format:check

      - name: Lint Check
        run: yarn run lint

      - name: Test
        run: yarn run test

      - name: Build
        run: yarn run build
